#! /bin/sh

# sxhkd startup
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Borders
bspc config active_border_color '#6e2084'
bspc config normal_border_color '#6e2084'
bspc config focused_border_color '#d292e5'

# Multi-lingual Input Method
fcitx5 -d &

# Live Wallpaper
xwinwrap -fs -fdt -ni -b -nf -un -o 1.0 -debug -- mpv -wid WID --loop --no-audio ~/.config/bspwm/outputascii_nerfed.mp4 &

# Flameshot exec
flameshot &

# Picom transparent windows
picom
# picom --experimental-backend --config ~/.config/picom/picom.conf -cfF -o 0.38 -O 200 -I 200 -t 0 -l 0 -r 3 -D2 -m 0.88
